version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: explore-api
    volumes:
      - .:/explore-api
    ports:
      - "8000:8000"
    environment:
      DATABASE_HOST: "aws-0-ap-south-1.pooler.supabase.com"  # Connect to host's localhost using host.docker.internal (for Docker Desktop)
      DATABASE_NAME: "postgres"  # Your local database name is "explore"
      DATABASE_USER: "postgres.utkokoitbjlirikqyyao"   # Replace with your local PostgreSQL username
      DATABASE_PASSWORD: "Explore@gdg#578" # Replace with your local PostgreSQL password
      DATABASE_PORT : "6543"

      # DATABASE_HOST: "host.docker.internal"  # Connect to host's localhost using host.docker.internal (for Docker Desktop)
      # DATABASE_NAME: "explore"  # Your local database name is "explore"
      # DATABASE_USER: "postgres"   # Replace with your local PostgreSQL username
      # DATABASE_PASSWORD: "Mongapost$2341" # Replace with your local PostgreSQL password
      # DATABASE_PORT : "5432"

      SECRET_KEY: "your_django_secret_key_here" # Replace with a real secret key
      DEBUG: "False" # Set DEBUG mode as needed